### ISSUE TITLE
Enhancement gate suggestions & Slowpoke bug

### ISSUE THREAD

**Issue by relinu** [InertSteak/Pokermon#32]
hi, i noticed a few things while playing the prerelease version and just wanted to let you know

enhancement gated cards
- maybe add an explanation for enhancement gated cards
- gating seems a bit "random"
- chansey & blissey are gated but happiny is not
- magnemite is gated but magneton & magnezone are not
- other evolution lines are fully gated (goldeen, rhyhorn, tangela, sandshrew)

slowpoke
- slowpoke cant be evolved with the kings rock from its effect (e.g. seed: 9W57TFPC)
- maybe nerf the effect chance, i had 3 rock cards in the time it took to evolve (6 extra gold)

**Comment by InertSteak** [comment]
Happiny doesn't rely on lucky cards it just makes them, so no need to gate it. 
Magnezone and magneton are oversights, I'll fix those. They should be gated. 

For slowpoke, you have to use kings rock on a card in order to use it. From my testing it evolves fine so maybe that's the issue.
Yeah, I'll change the chance to 1 in 5.

**Comment by relinu** [comment]
Happiny makes sense. How about changing its evo req to having something like 5 lucky cards? So its consistent with its evolutions. (Is that even possible?)

Kings rock was my dumbness, I thought it would generate a card like the other evo items.

Very nice mod btw :D
